### ISSUE TITLE
Can't find Eliza's package Racket-util

### ISSUE THREAD

**Issue by TureTex** [MarisaKirisame/PAIP#8]
Here is the error message:
> standard-module-name-resolver: collection not found
>   for module path: racket-util
>   collection: "racket-util"
>   in collection directories:
>    /root/.racket/6.5/collects
>    /usr/share/racket/collects
>    ... [155 additional linked and package directories] in: racket-util
>   no packages suggestions are available .
seems (require racket-util) can't find the package called racket-util, so where can I find it?

**Comment by MarisaKirisame** [comment]
http://github.com/MarisaKirisame/Racket-util
here you go
